default: program

program:
	g++ -g -o cachesim AtomicBusManager.cpp BusRequest.cpp BusResponse.cpp Cache.cpp CacheConstants.cpp CacheController.cpp CacheJob.cpp CacheLine.cpp CacheSet.cpp CacheStats.cpp

clean:
	-rm -f cachesim
